### ISSUE TITLE
separator between video info and watch buttons in hitchhiker layouts

### ISSUE THREAD

**Issue by TorutheRedFox** [lightbeam24/CustomTube#70]
this CSS (hastily) fixes the missing separator
```CSS
#bt-middle-row.bt-universalized-element::before {
  border-top: 1px solid rgb(65,65,65);
  height: 0px;
  width: calc(100% - 30px);
  left: 15px;
  padding: 0px;
  z-index: 0;
  content: "";
  display: inline-block;
  position: absolute;
}

#bt-ltod {
  z-index: 1;
}
```
